import { useState } from 'react';
import { getOverview, getTopRisk, getByDepartment } from '../api/analyticsApi';
import { getPredictionHistory } from '../api/predictionApi';
import { getAllEmployees } from '../api/employeeApi';
import LoadingSpinner from '../components/LoadingSpinner';
import toast from 'react-hot-toast';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const REPORTS = [
  { id: 'full_risk',    label: 'Full Employee Risk Report',   icon: 'chart',  desc: 'All employees with their latest risk scores' },
  { id: 'high_risk',   label: 'High Risk Employees Report',  icon: 'alert',  desc: 'Employees with risk score above 70%' },
  { id: 'department',  label: 'Department Summary Report',   icon: 'office', desc: 'Average risk score per department' },
  { id: 'predictions', label: 'Prediction History Report',   icon: 'list',   desc: 'All past predictions and recommendations' },
];

export default function ReportsPage() {
  const [previews, setPreviews] = useState({});
  const [loading, setLoading]   = useState({});

  // ── Fetch data for a report ────────────────────────────────────────
  const fetchPreview = async (id) => {
    setLoading(p => ({ ...p, [id]: true }));
    try {
      let data;
      if (id === 'full_risk') {
        const res = await getAllEmployees(1, '', '', 1000);
        data = (res.employees ?? res).map(e => ({
          Name:        `${e.first_name} ${e.last_name}`,
          Department:  e.department,
          'Job Role':  e.job_role,
          Income:      `$${e.monthly_income?.toLocaleString() ?? '—'}`,
          Overtime:    e.overtime ? 'Yes' : 'No',
          Satisfaction: e.job_satisfaction ?? '—',
        }));
      } else if (id === 'high_risk') {
        const res = await getTopRisk();
        data = res.filter(e => e.risk_score > 70).map(e => ({
          Name:          `${e.first_name} ${e.last_name}`,
          Department:    e.department,
          'Risk Score':  `${e.risk_score}%`,
          Prediction:    e.attrition_prediction,
          Recommendation: e.recommendation ?? '—',
        }));
      } else if (id === 'department') {
        const res = await getByDepartment();
        data = res.map(d => ({
          Department:      d.department,
          'Avg Risk Score': `${d.avg_risk_score}%`,
          'Employee Count': d.employee_count,
        }));
      } else {
        const res = await getPredictionHistory();
        data = res.map(p => ({
          Date:       p.created_at ? new Date(p.created_at).toLocaleDateString() : '—',
          Employee:   p.employee_name,
          'Model Used': p.model_used,
          'Risk Score': `${p.risk_score}%`,
          Prediction: p.attrition_prediction,
        }));
      }
      setPreviews(p => ({ ...p, [id]: data }));
    } catch { toast.error('Failed to load report data'); }
    finally { setLoading(p => ({ ...p, [id]: false })); }
  };

  // ── PDF download ───────────────────────────────────────────────────
  const downloadPDF = (id) => {
    const rows = previews[id];
    if (!rows?.length) return toast.error('Preview the report first');

    const report = REPORTS.find(r => r.id === id);
    const doc    = new jsPDF();
    const now    = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' });

    // Header bar
    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, 210, 28, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('HR Analytics Platform', 14, 12);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Employee Attrition Intelligence System', 14, 20);

    // Report title
    doc.setTextColor(30, 41, 59);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(report.label, 14, 40);

    // Meta line
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(`Generated on: ${now}   |   Total records: ${rows.length}`, 14, 48);

    // Divider
    doc.setDrawColor(203, 213, 225);
    doc.line(14, 52, 196, 52);

    // Table
    const columns = Object.keys(rows[0]);
    const tableRows = rows.map(r => columns.map(c => r[c] ?? '—'));

    autoTable(doc, {
      head: [columns],
      body: tableRows,
      startY: 56,
      styles: { fontSize: 8, cellPadding: 3 },
      headStyles: { fillColor: [59, 130, 246], textColor: 255, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      rowPageBreak: 'auto',
    });

    // Footer on every page
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(
        `Generated by HR Analytics Platform  |  Page ${i} of ${pageCount}`,
        105, 290, { align: 'center' }
      );
    }

    doc.save(`${id}_report_${new Date().toISOString().slice(0,10)}.pdf`);
    toast.success('PDF downloaded!');
  };

  // ── CSV download ───────────────────────────────────────────────────
  const downloadCSV = (id) => {
    const rows = previews[id];
    if (!rows?.length) return;
    const keys = Object.keys(rows[0]);
    const csv  = [keys.join(','), ...rows.map(r => keys.map(k => `"${r[k] ?? ''}"`).join(','))].join('\n');
    const a    = Object.assign(document.createElement('a'), {
      href: URL.createObjectURL(new Blob([csv], { type: 'text/csv' })),
      download: `${id}_${new Date().toISOString().slice(0,10)}.csv`,
    });
    a.click();
    toast.success('CSV downloaded!');
  };

  return (
    <div className="space-y-5">
      <p className="text-sm text-slate-500">Preview a report, then download as PDF or CSV.</p>

      {REPORTS.map(r => (
        <div key={r.id} className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
          {/* Header row */}
          <div className="flex items-center justify-between px-5 py-4 border-b border-slate-100">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-blue-50 text-blue-600 flex items-center justify-center flex-shrink-0">
                {r.icon === 'chart'  && <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.8}><path strokeLinecap="round" strokeLinejoin="round" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" /></svg>}
                {r.icon === 'alert'  && <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.8}><path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>}
                {r.icon === 'office' && <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.8}><path strokeLinecap="round" strokeLinejoin="round" d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" /></svg>}
                {r.icon === 'list'   && <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.8}><path strokeLinecap="round" strokeLinejoin="round" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01" /></svg>}
              </div>
              <div>
                <h3 className="font-semibold text-slate-800">{r.label}</h3>
                <p className="text-xs text-slate-500">{r.desc}</p>
              </div>
            </div>
            <div className="flex gap-2 flex-wrap justify-end">
              <button
                onClick={() => fetchPreview(r.id)}
                disabled={loading[r.id]}
                className="px-3 py-1.5 text-xs border border-slate-300 rounded-lg hover:bg-slate-50 transition-colors disabled:opacity-50"
              >
                {loading[r.id] ? 'Loading...' : 'Preview'}
              </button>
              {previews[r.id] && (
                <>
                  <button
                    onClick={() => downloadPDF(r.id)}
                    className="px-3 py-1.5 text-xs bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors font-medium"
                  >
                    Download PDF
                  </button>
                  <button
                    onClick={() => downloadCSV(r.id)}
                    className="px-3 py-1.5 text-xs bg-green-600 hover:bg-green-700 text-white rounded-lg transition-colors font-medium"
                  >
                    Download CSV
                  </button>
                </>
              )}
            </div>
          </div>

          {/* Preview table */}
          {loading[r.id] && <div className="p-4"><LoadingSpinner /></div>}
          {previews[r.id] && !loading[r.id] && (
            <div className="overflow-x-auto max-h-72">
              <table className="w-full text-xs">
                <thead className="bg-slate-50 sticky top-0">
                  <tr>
                    {Object.keys(previews[r.id][0]).map(k => (
                      <th key={k} className="text-left px-3 py-2 text-slate-500 font-semibold uppercase whitespace-nowrap border-b border-slate-200">
                        {k}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {previews[r.id].slice(0, 10).map((row, i) => (
                    <tr key={i} className="hover:bg-slate-50">
                      {Object.values(row).map((v, j) => (
                        <td key={j} className="px-3 py-2 text-slate-600 max-w-[160px] truncate">{String(v ?? '—')}</td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
              {previews[r.id].length > 10 && (
                <p className="text-xs text-center py-2 text-slate-400 border-t border-slate-100">
                  Showing 10 of {previews[r.id].length} rows — download for full data
                </p>
              )}
            </div>
          )}
        </div>
      ))}
    </div>
  );
}
